language: ruby
rvm:
  - 2.7.5
node_js:
  - node
services:
  - postgresql
install:
  - bundle config set --local deployment 'true'
  - bundle install --jobs=3 --retry=3 
  - nvm install
  - bin/yarn
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database sygrego_test;' -U postgres
  - RAILS_ENV=test bundle exec rails webpacker:compile
