language: ruby
rvm:
  - 2.6.6
node_js:
  - node
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database sygrego_test;' -U postgres
  - RAILS_ENV=test bundle exec rails webpacker:compile