language: ruby
rvm:
  - 2.6.6
node_js:
  - node
services:
  - postgresql
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install
  - bin/yarn
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database sygrego_test;' -U postgres
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - gem install gobject-introspection -v '3.4.9'