site_settings: &site_settings
# General settings
#    state_abbr: VIC
#    state_name: Victoria
#    camping_ground: Lardner Park
#    site_opening_month: March
    first_year: 1991
    conference_name: Conference of Churches of Christ in Victoria and Tasmania
    backend_website: https://sygrego.com
#    committee_name: committee
    state_area_code: 3
    abn: 264 033 23 495

# MySYG
    mysyg_default_enabled: true 
    mysyg_default_open: false
#    mysyg_default_approve_option: Tolerant
#    mysyg_default_participant_status: Accepted
#    allow_mysyg_to_be_closed: true 
#    allow_mysyg_approve_option: true

# Finance options
    cheque_payable: Churches of Christ Vic/Tas Inc.

# Email
    email_subject: "[SYG Registrations]"

# S3
    s3_region: us-east-1

development:  
    s3_bucket: sygrego-development

    <<: *site_settings

test:  
    s3_bucket: sygrego-test

    <<: *site_settings

production:  
    s3_bucket: sygrego

    <<: *site_settings
    
syg:  
    s3_bucket: tests3bucket

    <<: *site_settings
